/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_uned_secsoftdev_scoring_model_ScoringModel3 */

#ifndef _Included_es_uned_secsoftdev_scoring_model_ScoringModel3
#define _Included_es_uned_secsoftdev_scoring_model_ScoringModel3
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     es_uned_secsoftdev_scoring_model_ScoringModel3
 * Method:    event
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_es_uned_secsoftdev_scoring_model_ScoringModel3_event
  (JNIEnv *, jobject);

/*
 * Class:     es_uned_secsoftdev_scoring_model_ScoringModel3
 * Method:    score
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_es_uned_secsoftdev_scoring_model_ScoringModel3_score
  (JNIEnv *, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
